export const BASE_URL = "http://www.astrosagga.com/demo/api"
export const IMAGE_BASE_URL = "http://www.astrosagga.com/demo"
export const LOGIN = "/login"
export const LOGOUT = "/userLogout"

export const CATEGORY = "/categories-list"
export const SLIDERS = "/sliders"
export const ASTROLOGER = "/astrologer"
export const USERS = "/users"
export const PRODUCTCATEGORY = "/product-category"
export const BLOGS = "/blogs"
export const PRIVACYPOLICY = "/privacy-policy"
export const TERMCONDITION = "/terms-condition"
export const PRODUCTS = "/product"